### PR TITLE
Added alternate autoconf based build system that can support linux to windows cross compile

### PR DESCRIPTION
**Pull request by udif**
This PR is required for another PR for ADMeshGUI that adds automatic Windows builds using Linux to Windows cross compile.
This PR was required because I could not get premake4 to create the necessary Makefile for Linux to Windows cross compile,
while the autoconf system has excellent support for a cross compiler setup.
The files were adapted from the admesh build system.

### CODE REVIEW

**Comment by hroncok** [comment]
I'd rather only have one build system here and adapt the documentation for it.

**Comment by udif** [comment]
Can you help me make the changes to the pro make file so it will generate the correct makefiles for cross compilation when required?
In addition, the autoconf system generates an stlsplit.pc file that is used by pkg-conf during the build of ADMeshGUI to get the stlsplit correct c/c++ include path

**Comment by hroncok** [comment]
> Can you help me make the changes to the pro make file so it will generate the correct makefiles for cross compilation when required?

I thought this is what the PR does. Or is that not the case?

**Comment by udif** [comment]
No, this PR adds an alternate, autoconf-based build system on addition to the existing promake4-based one, because I didn't know how to handle Linux to windows cross compiles with promake4 (sounds like a niche case for it).

autoconf also gives me pkg-config files which are useful when I use stlsplit by the ADMeshGUI cross compile github action.

The original promake4 is left as-is and can be still used for other platforms.
The autoconf files were derived from the admesh autoconf files.

**Comment by hroncok** [comment]
Are you able to *replace* premake4 here entirely with autoconf?

**Comment by udif** [comment]
I've never used premake before until encountering it in stlsplit.
I did not want to spend too much time on [Yak shaving](https://en.wiktionary.org/wiki/yak_shaving) as my ultimate goal was to get an automatic Windows build for ADMeshGUI using github actions.
However, here is what I know about the issue so far:

__premake5 pros:__
- Potentially generate build scripts/makefiles/IDE confings for many tools and operating systems
- Conceptually simpler than GNU autoconf, at least for very simple projects (like this one).

__premake4 cons:__
- Already outdated, premake5 is already being developed already for years. Last stable release for premake4 was 11 years ago, and last beta was 8 years ago.
- No special support for cross compilation (At least, I haven't found it, in the relatively few hours I've spend on it)
- No special support for system installing of artifacts after compilation (ditto)

Since I didn't want to break anyone's code already using stlsplit with premake4, I decided to bolt-in the autotool code from admesh.
**Update:** Now that I look at it, admesh code is GPL2 while stlsplit and ADMeshGUI are AGPL3 which are incompatible.
I will need to either recreate the autoconf files from a clean room copy from a different AGPL3 project or write them myself from scratch (not a pretty task).
**Update2:** I'm now trying to use premake4, presently by using a simpler, separate premake4_cross.lua file, as I had issues trying to integrate my changes into the existing file. In order to do this, I decided to create a static library, not a shared library, since it is much simpler.
At the moment it still fails when linked by ADMeshGUI due to not finding stl_allocate() from admesh lib. I'm still looking into it.

**Comment by udif** [comment]
I managed to create a static library using only the default `premake4.lua` file by adding the static lib configuration as a new project. I still have to solve the ADMeshGUI build issue, it's probably due to linking order.

**Comment by udif** [comment]
I'm closing this PR because I've decided to drop the autoconf files:
1. It's forked from a GPL2-only repo and can't be used in a GPL3 repo without relicensing.
2. I have a much simpler solution for my issue based on creating a static library (I'll issue a new PR)

**Comment by udif** [comment]
Just one more note for anyone who reads this:

I have incorrectly asserted that admesh's license is GPL2-only and incompatible with stlsplit. I have came to this wrong conclusion because I was only looking at the license file itself ("COPYING").
Had I looked into the header at any of the code files, I would have seen the explicit permission to use the current GPL2 license, **or any later** license.

**Pull request closed without merging**
